name: CI

on: [push]

jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          submodules: recursive
#      - run: ./bin/build

  osx_test:
    name: Run tests on macOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up keychain
        run: |
          security create-keychain -p actions build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p actions build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k actions build.keychain
          security list-keychains -s build.keychain
      - run: cd test/providers/keychain && ./start && ./test
